Fix a couple redundant type conversions, use 'PKT' more often.
pkt-cash/pktd pull request #93
Opened 2020-10-26 01:37 UTC by johnsonjh

* Fixes a few seemingly unnecessary type conversions.,

  Double-check me on these, but they don't seem necessary:

  Ex: wire.NewTxOut(int64(satoshi), pkScript)
      blocksBetweenRetargets - (int32(blockHeight) % blocksBetweenRetargets)
  (Droping the int64 and int32 conversions, respectively._

 * Use the PKT name and unit where it applies.

2020-10-26 09:46 UTC, johnsonjh commented
Needs work, will resubmit later - possibly.

2020-10-26 13:14 UTC, johnsonjh commented
Actually, the problem I thought I had, I didn't have :+1: 

Still might need a rebase against your newest changes, this one is horribly invasive.

2020-10-29 16:19 UTC, cjdelisle commented on blockchain/chainio.go
> +//    - 0x32: VLQ-encoded compressed amount for 5000000000 (50 PKT)
This is false information, 50 PKT is not 5000000000, it's `2**30*50` or 53 687 091 200

2020-10-29 16:20 UTC, cjdelisle commented on blockchain/validate.go
> +	bitcoinBaseSubsidy := 50 * globalcfg.SatoshiPerPKT()
I prefer `UnitsPerCoin()` because we nominally do support syncing the bitcoin chain

2020-10-29 16:33 UTC, cjdelisle requested changes
Remove changes which create factual inaccuracy, we don't need to pretend Bitcoin doesn't exist, in theory this codebase should still be able to sync the Bitcoin chain so it's valid to speak about it.

Reformatting everything to a different width is bad because I can't read what really changed.

2020-10-29 16:33 UTC, cjdelisle commented on chaincfg/globalcfg/config.go
> +			{Name: "kBTC", Units: int64(1) << 30 * 1e3, Zeros: 15},
?

2020-10-29 16:33 UTC, cjdelisle commented on chaincfg/globalcfg/util.go
> +// value to the nearest Amount.
this is annoying because it's changing absolutely everything

2020-10-29 16:33 UTC, cjdelisle commented on config.go
> +	MinRelayTxFee        float64       `long:"minrelaytxfee" description:"The minimum transaction fee in PKT/kB to be considered a non-zero fee."`
coins/kB

2020-10-29 16:33 UTC, cjdelisle commented on btcutil/amount.go
> +func (a Amount) ToPKT() float64 {
ToCoins()

2020-10-29 19:07 UTC, johnsonjh commented
Applying fixes as requested.

2020-10-29 19:10 UTC, johnsonjh commented on chaincfg/globalcfg/config.go
> +			{Name: "kBTC", Units: int64(1) << 30 * 1e3, Zeros: 15},
Fixing.

2020-10-29 19:11 UTC, johnsonjh commented on chaincfg/globalcfg/util.go
> +// value to the nearest Amount.
Will revert any added comment formatting changes.

2020-10-29 19:15 UTC, johnsonjh commented on blockchain/chainio.go
> +//    - 0x32: VLQ-encoded compressed amount for 5000000000 (50 PKT)
Will correct.

2020-10-29 19:15 UTC, johnsonjh commented on blockchain/validate.go
> +	bitcoinBaseSubsidy := 50 * globalcfg.SatoshiPerPKT()
Changing to UnitsPerCoin()

2020-10-29 19:18 UTC, johnsonjh commented on config.go
> +	MinRelayTxFee        float64       `long:"minrelaytxfee" description:"The minimum transaction fee in PKT/kB to be considered a non-zero fee."`
Got it, will generalize as requested.

2020-10-29 19:50 UTC, johnsonjh commented
> Applying fixes as requested.

Done, pushed.

2020-10-30 04:10 UTC, cjdelisle commented on blockchain/chainio.go
> +//      - 0x91f20f: VLQ-encoded compressed amount for 34405000000 (344.05 PKT)
I didn't comment every single line with a problem, this has exactly the same problem as the line above, I'm going to close this because it's wasting my time.

2020-10-30 04:10 UTC, closed without merging

2020-10-30 04:52 UTC, johnsonjh commented on blockchain/chainio.go
> +//      - 0x91f20f: VLQ-encoded compressed amount for 34405000000 (344.05 PKT)
No problem, it was mostly automated changes - I'll pull out the only functional change which are the redundant type conversions and just toss the rest.